javascripts:
  analytics:
    - public/javascripts/g-analytics.js
  libraries:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/jquery-ui*.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/preload.js
    - public/javascripts/application.js
  mobile_libraries:
    - public/javascripts/jquery-1.5.2*.js
    - public/javascripts/jquery.mobile*.js
  mobile:
    #- public/javascripts/mobile.js

stylesheets:
  main:
    - public/stylesheets/reset.css
    - public/stylesheets/mixins.css
    - public/stylesheets/stylesheet.css
    - public/stylesheets/calendar.css
    - public/stylesheets/categories.css
  mobile:
    - public/stylesheets/jquery.mobile*.css
    - public/stylesheets/mobile.css

