javascripts:
  libraries:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/jquery-ui*.js
  plugins:
    - public/javascripts/preloadCssImages.jQuery_v5.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/application.js
  mobile_libraries:
    - public/javascripts/jquery-1.5.2.min.js
  mobile_plugins:
    - public/javascripts/jQuery.ui.datepicker.js
    - public/javascripts/jquery.ui.datepicker.mobile.js
    - public/javascripts/jquery.mobile*.js
  mobile:
    #- public/javascripts/mobile.js
  analytics:
    - public/javascripts/g-analytics.js

stylesheets:
  main:
    - public/stylesheets/reset.css
    - public/stylesheets/mixins.css
    - public/stylesheets/stylesheet.css
    - public/stylesheets/calendar.css
    - public/stylesheets/categories.css
  mobile:
    - public/stylesheets/jquery.mobile*.css
    - public/stylesheets/jquery.ui.datepicker.mobile.css
    - public/stylesheets/mobile.css

